# Generated by Django 2.2 on 2019-05-08 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_surface', models.IntegerField()),
                ('max_surface', models.IntegerField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.Country')),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.PropertyType')),
            ],
            options={
                'verbose_name': 'Alerte de rescherche',
                'verbose_name_plural': 'Alertes de rescherche',
            },
        ),
    ]
