# Generated by Django 2.2 on 2019-05-08 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_auto_20190508_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='property/uploads/gallery'),
        ),
    ]
